version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=informacion_tribus
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8082:8082"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone